spring:
  datasource:
    url: ${AGGREGATION_PRIMARY_JDBC_URL}
    username: ${AGGREGATION_PRIMARY_JDBC_USERNAME}
    password: ${AGGREGATION_PRIMARY_JDBC_PASSWORD}
  data:
    mongodb:
      uri: ${AGGREGATION_MONGODB_URI}
